### ISSUE TITLE
Add a function to the token contract to get the admin

### ISSUE THREAD

**Issue by leighmcculloch** [stellar/rs-soroban-env#541] opened 2022-10-18 00:06 UTC
I propose we add a function to the token contract that returns the admin.

There's no way from outside the token contract to introspect who the admin is. This seems like trivial thing to add. The contract already exposes other details about itself.

The use case is for contracts who wish to check if a participant in their invocations has any special capabilities for the token contract.

Another use case is for general ability for dapps and other tools to ask a contract who its admin is, without having to introspect actual contract data which we decided early on to avoid doing and to learn into providing read functions.

**Comment by willemneal** [comment] 2022-10-18 00:11
Is admin the same as owner in tbis context?

**Comment by leighmcculloch** [comment] 2022-10-18 00:16
It is. It is essentially the same concept as an "issuer" on Stellar today, although it can be more than a Stellar account as it can also be another contract or an ed25519 key independent of any account.

**Comment by leighmcculloch** [comment] 2022-10-18 00:17
> This seems like trivial thing to add.

I overlooked one aspect that does make this a little less trivial to implement: the Native token contract deployment has no admin. The function probably shouldn't 💥 when called on the native contract.

**Comment by leighmcculloch** [comment] 2022-10-18 18:47
The `admin` function could return `Option<Identifier>`, but then its utility seems less useful if it can sometimes not be set. This seems less useful if it doesn't always have a value, and could be the cause of a contract being brittle. I'm leaning towards closing this as 'not planned' unless anyone can see a need.

(I had a specific use, but that use has evaporated for unrelated reasons.)

**Comment by sisuresh** [comment] 2023-06-02 16:49
Duplicate of https://github.com/stellar/rs-soroban-env/issues/635

**Closed by sisuresh** 2023-06-02 16:49 UTC
